const nationalTeamNamesKo: Record<string, string> = {
  ARG: "아르헨티나",
  AUS: "호주",
  AUT: "오스트리아",
  BEL: "벨기에",
  BIH: "보스니아 헤르체고비나",
  BRA: "브라질",
  CAN: "캐나다",
  CHE: "스위스",
  CIV: "코트디부아르",
  COD: "콩고민주공화국",
  COL: "콜롬비아",
  CPV: "카보베르데",
  CUW: "퀴라소",
  CZE: "체코",
  DZA: "알제리",
  ECU: "에콰도르",
  EGY: "이집트",
  ENG: "잉글랜드",
  ESP: "스페인",
  FRA: "프랑스",
  GER: "독일",
  GHA: "가나",
  HRV: "크로아티아",
  HTI: "아이티",
  IRN: "이란",
  IRQ: "이라크",
  JOR: "요르단",
  JPN: "일본",
  KOR: "대한민국",
  MAR: "모로코",
  MEX: "멕시코",
  NLD: "네덜란드",
  NOR: "노르웨이",
  NZL: "뉴질랜드",
  PAN: "파나마",
  PAR: "파라과이",
  PRT: "포르투갈",
  QAT: "카타르",
  RSA: "남아프리카공화국",
  SAU: "사우디아라비아",
  SCT: "스코틀랜드",
  SEN: "세네갈",
  SUI: "스위스",
  SWE: "스웨덴",
  TUN: "튀니지",
  TUR: "튀르키예",
  URY: "우루과이",
  USA: "미국",
  UZB: "우즈베키스탄",
};

// WC 2026 국가대표 (football-data.org 영어명 기준)
const nationalTeamEnNamesKo: Record<string, string> = {
  Argentina: "아르헨티나",
  Australia: "호주",
  Austria: "오스트리아",
  Belgium: "벨기에",
  "Bosnia-Herzegovina": "보스니아 헤르체고비나",
  Brazil: "브라질",
  Canada: "캐나다",
  Switzerland: "스위스",
  "Ivory Coast": "코트디부아르",
  "Congo DR": "콩고민주공화국",
  Colombia: "콜롬비아",
  "Cape Verde Islands": "카보베르데",
  "Curaçao": "퀴라소",
  Czechia: "체코",
  Algeria: "알제리",
  Ecuador: "에콰도르",
  Egypt: "이집트",
  England: "잉글랜드",
  Spain: "스페인",
  France: "프랑스",
  Germany: "독일",
  Ghana: "가나",
  Croatia: "크로아티아",
  Haiti: "아이티",
  Iran: "이란",
  Iraq: "이라크",
  Jordan: "요르단",
  Japan: "일본",
  "Korea Republic": "대한민국",
  "South Korea": "대한민국",
  Morocco: "모로코",
  Mexico: "멕시코",
  Netherlands: "네덜란드",
  Norway: "노르웨이",
  "New Zealand": "뉴질랜드",
  Panama: "파나마",
  Paraguay: "파라과이",
  Portugal: "포르투갈",
  Qatar: "카타르",
  "South Africa": "남아프리카공화국",
  "Saudi Arabia": "사우디아라비아",
  Scotland: "스코틀랜드",
  Senegal: "세네갈",
  Sweden: "스웨덴",
  Tunisia: "튀니지",
  Turkey: "튀르키예",
  Uruguay: "우루과이",
  "United States": "미국",
  Uzbekistan: "우즈베키스탄",
};

// 유럽 5대 리그 클럽팀 (football-data.org 영어명 기준)
const clubTeamNamesKo: Record<string, string> = {
  // 프리미어리그 (PL)
  "Arsenal FC": "아스날",
  Arsenal: "아스날",
  "Aston Villa FC": "아스톤 빌라",
  "Aston Villa": "아스톤 빌라",
  "AFC Bournemouth": "본머스",
  Bournemouth: "본머스",
  "Brentford FC": "브렌트퍼드",
  Brentford: "브렌트퍼드",
  "Brighton & Hove Albion FC": "브라이턴",
  Brighton: "브라이턴",
  "Chelsea FC": "첼시",
  Chelsea: "첼시",
  "Crystal Palace FC": "크리스털 팰리스",
  "Crystal Palace": "크리스털 팰리스",
  "Everton FC": "에버턴",
  Everton: "에버턴",
  "Fulham FC": "풀럼",
  Fulham: "풀럼",
  "Ipswich Town FC": "입스위치 타운",
  "Ipswich Town": "입스위치 타운",
  "Leeds United FC": "리즈 유나이티드",
  "Leeds United": "리즈 유나이티드",
  "Liverpool FC": "리버풀",
  Liverpool: "리버풀",
  "Manchester City FC": "맨체스터 시티",
  "Manchester City": "맨체스터 시티",
  "Manchester United FC": "맨체스터 유나이티드",
  "Manchester United": "맨체스터 유나이티드",
  "Newcastle United FC": "뉴캐슬 유나이티드",
  "Newcastle United": "뉴캐슬 유나이티드",
  "Nottingham Forest FC": "노팅엄 포레스트",
  "Nottingham Forest": "노팅엄 포레스트",
  "Sunderland AFC": "선덜랜드",
  Sunderland: "선덜랜드",
  "Tottenham Hotspur FC": "토트넘 홋스퍼",
  "Tottenham Hotspur": "토트넘 홋스퍼",
  Tottenham: "토트넘 홋스퍼",
  "West Ham United FC": "웨스트햄 유나이티드",
  "Wolverhampton Wanderers FC": "울버햄튼",
  "Coventry City FC": "코번트리 시티",
  "Hull City AFC": "헐 시티",
  "Leicester City FC": "레스터 시티",
  "Luton Town FC": "루턴 타운",
  "Sheffield United FC": "셰필드 유나이티드",
  "Burnley FC": "번리",
  "Southampton FC": "사우샘프턴",

  // 라리가 (PD)
  "FC Barcelona": "FC 바르셀로나",
  Barcelona: "FC 바르셀로나",
  "Real Madrid CF": "레알 마드리드",
  "Real Madrid": "레알 마드리드",
  "Club Atlético de Madrid": "아틀레티코 마드리드",
  "Atlético Madrid": "아틀레티코 마드리드",
  "Sevilla FC": "세비야",
  Sevilla: "세비야",
  "Real Betis Balompié": "레알 베티스",
  "Real Betis": "레알 베티스",
  "Villarreal CF": "비야레알",
  Villarreal: "비야레알",
  "Athletic Club": "아틀레틱 빌바오",
  "Real Sociedad de Fútbol": "레알 소시에다드",
  "Real Sociedad": "레알 소시에다드",
  "CA Osasuna": "오사수나",
  Osasuna: "오사수나",
  "Valencia CF": "발렌시아",
  Valencia: "발렌시아",
  "RCD Espanyol de Barcelona": "에스파뇰",
  Espanyol: "에스파뇰",
  "Getafe CF": "헤타페",
  Getafe: "헤타페",
  "Rayo Vallecano de Madrid": "라요 바예카노",
  "Rayo Vallecano": "라요 바예카노",
  "Girona FC": "지로나",
  Girona: "지로나",
  "RC Celta de Vigo": "셀타 비고",
  "Celta Vigo": "셀타 비고",
  "Deportivo Alavés": "알라베스",
  Alavés: "알라베스",
  "RCD Mallorca": "마요르카",
  Mallorca: "마요르카",
  "Real Oviedo": "레알 오비에도",
  "Elche CF": "엘체",
  Elche: "엘체",
  "Levante UD": "레반테",
  Levante: "레반테",
  "UD Las Palmas": "라스팔마스",
  "Cádiz CF": "카디스",

  // 분데스리가 (BL1)
  "FC Bayern München": "바이에른 뮌헨",
  "Bayern Munich": "바이에른 뮌헨",
  "Borussia Dortmund": "보루시아 도르트문트",
  "Bayer 04 Leverkusen": "바이어 레버쿠젠",
  "Bayer Leverkusen": "바이어 레버쿠젠",
  "RB Leipzig": "RB 라이프치히",
  "Borussia Mönchengladbach": "보루시아 묀헨글라트바흐",
  "Eintracht Frankfurt": "아인트라흐트 프랑크푸르트",
  "VfB Stuttgart": "VfB 슈투트가르트",
  Stuttgart: "VfB 슈투트가르트",
  "SC Freiburg": "SC 프라이부르크",
  Freiburg: "SC 프라이부르크",
  "SV Werder Bremen": "베르더 브레멘",
  "Werder Bremen": "베르더 브레멘",
  "TSG 1899 Hoffenheim": "TSG 호펜하임",
  Hoffenheim: "TSG 호펜하임",
  "FC Augsburg": "FC 아우크스부르크",
  Augsburg: "FC 아우크스부르크",
  "1. FSV Mainz 05": "마인츠 05",
  "FSV Mainz 05": "마인츠 05",
  "VfL Wolfsburg": "볼프스부르크",
  Wolfsburg: "볼프스부르크",
  "FC St. Pauli 1910": "FC 장크트 파울리",
  "St. Pauli": "FC 장크트 파울리",
  "1. FC Heidenheim 1846": "FC 하이덴하임",
  Heidenheim: "FC 하이덴하임",
  "1. FC Köln": "FC 쾰른",
  Köln: "FC 쾰른",
  "1. FC Union Berlin": "우니온 베를린",
  "Union Berlin": "우니온 베를린",
  "Hamburger SV": "함부르크 SV",
  "VfL Bochum 1848": "VfL 보훔",
  "VfL Bochum": "VfL 보훔",

  // 세리에 A (SA)
  "FC Internazionale Milano": "인테르 밀란",
  Inter: "인테르 밀란",
  "Internazionale": "인테르 밀란",
  "AC Milan": "AC 밀란",
  Milan: "AC 밀란",
  "Juventus FC": "유벤투스",
  Juventus: "유벤투스",
  "AS Roma": "AS 로마",
  Roma: "AS 로마",
  "SS Lazio": "SS 라치오",
  Lazio: "SS 라치오",
  "ACF Fiorentina": "피오렌티나",
  Fiorentina: "피오렌티나",
  "SSC Napoli": "나폴리",
  Napoli: "나폴리",
  "Atalanta BC": "아탈란타",
  Atalanta: "아탈란타",
  "Bologna FC 1909": "볼로냐",
  Bologna: "볼로냐",
  "Torino FC": "토리노",
  Torino: "토리노",
  "Udinese Calcio": "우디네세",
  Udinese: "우디네세",
  "Cagliari Calcio": "칼리아리",
  Cagliari: "칼리아리",
  "Genoa CFC": "제노아",
  Genoa: "제노아",
  "Hellas Verona FC": "엘라스 베로나",
  "Hellas Verona": "엘라스 베로나",
  "US Lecce": "레체",
  Lecce: "레체",
  "Parma Calcio 1913": "파르마",
  Parma: "파르마",
  "Como 1907": "코모",
  Como: "코모",
  "Monza": "몬차",
  "US Sassuolo Calcio": "사수올로",
  Sassuolo: "사수올로",
  "US Cremonese": "크레모네세",
  "AC Pisa 1909": "AC 피사",
  Pisa: "AC 피사",
  "Empoli FC": "엠폴리",
  "Frosinone Calcio": "프로시노네",

  // 리그 1 (FL1)
  "Paris Saint-Germain FC": "파리 생제르맹",
  "Paris Saint-Germain": "파리 생제르맹",
  PSG: "파리 생제르맹",
  "AS Monaco FC": "AS 모나코",
  Monaco: "AS 모나코",
  "Olympique Lyonnais": "올랭피크 리옹",
  Lyon: "올랭피크 리옹",
  "Olympique de Marseille": "올랭피크 마르세유",
  Marseille: "올랭피크 마르세유",
  "Lille OSC": "릴",
  Lille: "릴",
  "OGC Nice": "OGC 니스",
  Nice: "OGC 니스",
  "Stade Rennais FC 1901": "스타드 렌",
  Rennes: "스타드 렌",
  "RC Strasbourg Alsace": "RC 스트라스부르",
  Strasbourg: "RC 스트라스부르",
  "Racing Club de Lens": "RC 랑스",
  Lens: "RC 랑스",
  "AJ Auxerre": "AJ 오세르",
  Auxerre: "AJ 오세르",
  "Angers SCO": "앙제",
  Angers: "앙제",
  "Stade Brestois 29": "스타드 브레스트",
  Brest: "스타드 브레스트",
  "ES Troyes AC": "ES 트루아",
  Troyes: "ES 트루아",
  "Le Havre AC": "르아브르",
  "Le Havre": "르아브르",
  "Toulouse FC": "툴루즈",
  Toulouse: "툴루즈",
  "Paris FC": "파리 FC",
  "FC Lorient": "FC 로리앙",
  Lorient: "FC 로리앙",
  "Le Mans FC": "르망 FC",
  "RC Lens": "RC 랑스",
  "Nantes": "낭트",
  "Montpellier HSC": "몽펠리에",
  "Clermont Foot": "클레르몽",
  "ESTAC Troyes": "ES 트루아",
};

export function localizeTeamName(shortName: string | null, fallback: string): string {
  if (shortName) {
    // 1. TLA 코드 기반 (OpenLigaDB 국가대표: "ARG", "ENG", "MEX/ENG" 등)
    const codes = shortName.split("/");
    const byCode = codes.map((code) => nationalTeamNamesKo[code]);
    if (byCode.every(Boolean)) return byCode.join("/");

    // 2. 영어 short_name 기반 (football-data.org: "Arsenal FC", "Argentina" 등)
    const byShort = clubTeamNamesKo[shortName] ?? nationalTeamEnNamesKo[shortName];
    if (byShort) return byShort;
  }

  // 3. full name 기반 폴백 (short_name이 없거나 미매핑인 경우)
  return clubTeamNamesKo[fallback] ?? nationalTeamEnNamesKo[fallback] ?? fallback;
}

export function localizeCompetitionName(name: string, code?: string | null): string {
  const namesByCode: Record<string, string> = {
    WC: "2026 FIFA 월드컵",
    PL: "프리미어리그",
    PD: "라리가",
    BL1: "분데스리가",
    SA: "세리에 A",
    FL1: "리그 1",
  };
  if (code && namesByCode[code]) return namesByCode[code];
  return /^WM\s+2026$/i.test(name) ? "2026 FIFA 월드컵" : name;
}

export function localizeStage(stage: string | null): string | undefined {
  if (!stage) return undefined;
  const groupMatch = /^Gruppenphase\s+(\d+)$/i.exec(stage);
  if (groupMatch) return `조별리그 ${groupMatch[1]}차전`;

  const stages: Record<string, string> = {
    Sechzehntelfinale: "32강",
    Achtelfinale: "16강",
    Viertelfinale: "8강",
    Halbfinale: "준결승",
    Finale: "결승",
    "Spiel um Platz 3": "3·4위전",
  };
  return stages[stage] ?? stage;
}

export function localizePlayerName(name: string): string {
  const normalized = name.replace(/&apos;/g, "'").replace(/\s+/g, " ").trim();
  return playerNamesKo[normalized] ?? normalized;
}

const playerNamesKo: Record<string, string> = {
  // 현재 수집 중인 이적 피드
  "J. Sancho": "제이든 산초",
  "Ethan Williams": "이선 윌리엄스",
  "E. Wheatley": "이선 휘틀리",
  "J. Devaney": "잭 데버니",
  "J. Scanlon": "제임스 스캔런",
  "C. Scanlon": "캘럼 스캔런",
  "L. Chambers": "루크 챔버스",
  "L. Koumas": "루이스 쿠마스",
  "Luca Stephenson": "루카 스티븐슨",
  "Isaac Mabaya": "아이작 마바야",
  "Ismeal Kabia": "이스밀 카비아",
  "Louie George Copley": "루이 조지 코플리",
  "Daniel Gore": "댄 고어",
  "Fabian Mrozek": "파비안 므로제크",
  "Trent Toure Kone Doherty": "트렌트 코네도허티",
  "Lee Jonas": "리 조나스",
  "D. Oyetunde": "다니엘 오예툰데",
  "C. Sagoe": "찰스 사고 주니어",
  "Edward Ibrovic-Fletcher": "에드워드 이브로비치플레처",
  "S. Koné": "세쿠 코네",
  "Osman Kamara": "오스만 카마라",
  "Jaden Dixon": "제이든 딕슨",
  "H. Davies": "하비 데이비스",
  "O. Zinchenko": "올렉산드르 진첸코",
  "R. Bennett": "리스 베넷",
  "Tobias Christopher Collyer": "토비 콜리어",
  "M. Kacurri": "말디니 카쿠리",
  "J. Hugill": "조 휴길",
  "S. Lonmeni": "사무엘 롱메니",
  "S. Oulad M'Hand": "살라에딘 울라드 음핸드",
  "H. Amass": "해리 아마스",
  "E. Nwaneri": "에단 은와네리",
  "Samuel Mather": "샘 매더",
  "Elyh Harrison": "엘라이 해리슨",
  "H. Ogunneye": "하비브 오군네예",
  "J. McConnell": "제임스 매코널",
  "Louis Jackson": "루이스 잭슨",
  "J. Balagizi": "제임스 발라기지",
  "O. Beck": "오언 벡",
  "Sonny Aljofree": "소니 알조프리",
  "James Barry Norris": "제임스 노리스",
  "T. Tomiyasu": "도미야스 다케히로",
  "A. Onana": "안드레 오나나",
  "C. Eriksen": "크리스티안 에릭센",
  "V. Lindelöf": "빅토르 린델뢰프",

  // 아르헨티나
  "Lionel Messi": "리오넬 메시",
  "L. Messi": "리오넬 메시",
  "Julián Álvarez": "훌리안 알바레스",
  "J. Álvarez": "훌리안 알바레스",
  "Lautaro Martínez": "라우타로 마르티네스",

  // 프랑스
  "Kylian Mbappé": "킬리안 음바페",
  "K. Mbappé": "킬리안 음바페",
  "Antoine Griezmann": "앙투안 그리에즈만",
  "A. Griezmann": "앙투안 그리에즈만",
  "Ousmane Dembélé": "우스만 뎀벨레",
  "O. Dembélé": "우스만 뎀벨레",
  "Marcus Thuram": "마르쿠스 튀랑",
  "Aurélien Tchouaméni": "오렐리앙 추아메니",

  // 잉글랜드
  "Jude Bellingham": "주드 벨링엄",
  "J. Bellingham": "주드 벨링엄",
  "Harry Kane": "해리 케인",
  "H. Kane": "해리 케인",
  "Bukayo Saka": "부카요 사카",
  "B. Saka": "부카요 사카",
  "Phil Foden": "필 포든",
  "P. Foden": "필 포든",
  "Declan Rice": "데클런 라이스",
  "D. Rice": "데클런 라이스",
  "Raheem Sterling": "라힘 스털링",
  "Marcus Rashford": "마커스 래시퍼드",
  "M. Rashford": "마커스 래시퍼드",
  "Trent Alexander-Arnold": "트렌트 알렉산더-아널드",
  "T. Alexander-Arnold": "트렌트 알렉산더-아널드",

  // 브라질
  "Vinicius Junior": "비니시우스 주니어",
  "Vinicius Jr.": "비니시우스 주니어",
  "V. Junior": "비니시우스 주니어",
  "Rodrygo": "호드리구",
  "Neymar": "네이마르",
  "Richarlison": "히샬리송",

  // 스페인
  "Pedri": "페드리",
  "Gavi": "가비",
  "Lamine Yamal": "라민 야말",
  "L. Yamal": "라민 야말",
  "Ferran Torres": "페란 토레스",
  "Dani Olmo": "다니 올모",
  "Álvaro Morata": "알바로 모라타",

  // 독일
  "Jamal Musiala": "야말 무시알라",
  "J. Musiala": "야말 무시알라",
  "Florian Wirtz": "플로리안 비르츠",
  "F. Wirtz": "플로리안 비르츠",
  "Leroy Sané": "르루아 사네",
  "Thomas Müller": "토마스 뮐러",
  "T. Müller": "토마스 뮐러",
  "Joshua Kimmich": "요수아 키미히",
  "J. Kimmich": "요수아 키미히",
  "Leon Goretzka": "레온 고레츠카",
  "Manuel Neuer": "마누엘 노이어",
  "Kai Havertz": "카이 하버츠",

  // 포르투갈
  "Cristiano Ronaldo": "크리스티아누 호날두",
  "C. Ronaldo": "크리스티아누 호날두",
  "Bernardo Silva": "베르나르두 실바",
  "B. Silva": "베르나르두 실바",
  "Bruno Fernandes": "브루누 페르난데스",
  "B. Fernandes": "브루누 페르난데스",
  "Rafael Leão": "하파엘 레앙",
  "R. Leão": "하파엘 레앙",
  "João Félix": "주앙 펠릭스",
  "Diogo Jota": "지오고 조타",
  "Rúben Dias": "루벤 디아스",

  // 네덜란드
  "Virgil van Dijk": "비르힐 판 데이크",
  "V. van Dijk": "비르힐 판 데이크",
  "Memphis Depay": "멤피스 더파이",
  "Cody Gakpo": "코디 가크포",
  "Xavi Simons": "하비 시몬스",
  "Brian Brobbey": "브리안 브로베이",
  "Wout Weghorst": "바웃 베호르스트",

  // 벨기에
  "Kevin De Bruyne": "케빈 더 브라위너",
  "K. De Bruyne": "케빈 더 브라위너",
  "Romelu Lukaku": "로멜루 루카쿠",
  "Thibaut Courtois": "티보 쿠르투아",
  "T. Courtois": "티보 쿠르투아",

  // 노르웨이
  "Erling Haaland": "얼링 홀란",
  "E. Haaland": "얼링 홀란",
  "Martin Ødegaard": "마르틴 외데고르",

  // 모로코
  "Achraf Hakimi": "아슈라프 하키미",
  "A. Hakimi": "아슈라프 하키미",
  "Hakim Ziyech": "하킴 지예흐",
  "Sofiane Boufal": "소피안 부팔",
  "Soufiane Rahimi": "수피안 라히미",
  "Ismael Saibari": "이스마엘 사이바리",
  "Azzedine Ounahi": "아제딘 우나히",
  "Yassine Bounou": "야신 부누",

  // 대한민국
  "Son Heung-min": "손흥민",
  "Heung-min Son": "손흥민",
  "H. Son": "손흥민",
  "Lee Jae-sung": "이재성",
  "Hwang Hee-chan": "황희찬",
  "Kim Min-jae": "김민재",
  "Cho Gue-sung": "조규성",

  // 일본
  "Takehiro Tomiyasu": "도미야스 다케히로",
  "Takumi Minamino": "미나미노 다쿠미",
  "Kaoru Mitoma": "미토마 가오루",
  "Ritsu Doan": "도안 리쓰",
  "Daichi Kamada": "가마다 다이치",
  "Ayase Ueda": "우에다 아야세",

  // 멕시코
  "Julián Quiñones": "훌리안 키뇨네스",
  "J. Quiñones": "훌리안 키뇨네스",
  "Hirving Lozano": "이르빙 로사노",
  "H. Lozano": "이르빙 로사노",
  "Guillermo Ochoa": "기예르모 오초아",
  "Raúl Jiménez": "라울 히메네스",
  "Raul Jiminez": "라울 히메네스",

  // 클럽 선수 (PL/UCL 등)
  "Mohamed Salah": "모하메드 살라",
  "M. Salah": "모하메드 살라",
  "Roberto Firmino": "호베르투 피르미누",
  "Andrew Robertson": "앤드루 로버트슨",
  "Alexis Mac Allister": "알렉시스 맥 알리스터",
  "Darwin Núñez": "다윈 누녜스",
  "Robert Lewandowski": "로베르트 레반도프스키",
  "R. Lewandowski": "로베르트 레반도프스키",
  "Jack Grealish": "잭 그릴리시",
  "Rodri": "로드리",
  "Kyle Walker": "카일 워커",
  "Ilkay Gündogan": "일카이 귄도안",
  "İlkay Gündoğan": "일카이 귄도안",
  "Sadio Mané": "사디오 마네",
  "S. Mané": "사디오 마네",
  "Kylian Mbappe": "킬리안 음바페",
  "Riyad Mahrez": "리야드 마레즈",
  "Karim Benzema": "카림 벤제마",
  "K. Benzema": "카림 벤제마",
  "Luka Modrić": "루카 모드리치",
  "L. Modrić": "루카 모드리치",
  "Toni Kroos": "토니 크로스",
  "Casemiro": "카세미루",
  "Mikel Oyarzabal": "미켈 오야르사발",
  "Ismaïla Sarr": "이스마일라 사르",
  "Yoane Wissa": "요안 위사",
  "Matheus Cunha": "마테우스 쿠냐",
  "Jonathan David": "조너선 데이비드",
  "Folarin Balogun": "폴라린 발로건",
  "Deniz Undav": "데니즈 운다브",
  "Youri Tielemans": "유리 틸레만스",
  "Ruben Vargas": "루벤 바르가스",
  "Nicolas Pépé": "니콜라 페페",
  "Leandro Trossard": "레안드로 트로사르",
  "Daniel Muñoz": "다니엘 무뇨스",
  "Cyrensio Summerville": "크리센시오 서머빌",
  "Cyle Larin": "사일 라린",
  "Charles De Ketelaere": "샤를 더케텔라러",
  "Breel Embolo": "브릴 엠볼로",
  "Bradley Barcola": "브래들리 바르콜라",
  "Anthony Elanga": "안토니 엘랑가",
  "Amad Diallo": "아마드 디알로",
  "Viktor Gyökeres": "빅토르 요케레스",
  "Teun Koopmeiners": "퇸 코프메이너르스",
  "Stephen Eustáquio": "스티븐 에우스타키우",
  "Pedro Porro": "페드로 포로",
};
